name: publishes project documentation
on: [push]

env: 
    python_venv_dir: "anansi_python_env"
    NCP_TOP_LEVEL: "$CI_PROJECT_DIR" 
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: echo $GITHUB_ACTION_PATH
      - run: ls -l $GITHUB_ACTION_PATH/bin
